### PR TITLE
Wd add multibody

### PR DESCRIPTION
**Pull request by thisisaus**
Added simple multibody / polynomial format example with a 3d visualization

### CODE REVIEW

**Review by babakqci — APPROVED** [review]
Look good to me. I'd labels to the 3D plot, "x", "y", and "f(x,y)"

**Comment by thisisaus** [comment]
> Look good to me. I'd labels to the 3D plot, "x", "y", and "f(x,y)"

Added labels

**Review by babakqci — APPROVED** [review]

**Review by rafikalid — DISMISSED** [review]

**Review by RussellHuffman — CHANGES_REQUESTED** [review]
I did a copy review and it looks fine. Can you change the name of the tutorial to be "Multibody-on-Dirac" so that it follows the convention of the other tutorials? Otherwise this is fine.

**Comment by RussellHuffman** [comment]
@nchancellor-qci, Can you add to your backlog to give this tutorial a similar treatment as the other tutorials? Adding "introduction", "importance", and "applications" paragraphs will be really helpful here.

But I don't want this to be a blocker. The tutorial can be published first, and then the additional context added after the first release.

**Comment by nchancellor-qci** [comment]
> @nchancellor-qci, Can you add to your backlog to give this tutorial a similar treatment as the other tutorials? Adding "introduction", "importance", and "applications" paragraphs will be really helpful here.
> 
> But I don't want this to be a blocker. The tutorial can be published first, and then the additional context added after the first release.

Definitely, I think this is a good structure and one we should use for all tutorials.

**Review by RussellHuffman — APPROVED** [review]
I made the naming changes. that seemed to be the only blocker, so this is now approved.

**Pull request merged**
