### PR TITLE
Added a tutorial for eqc model qboost library

### PR DESCRIPTION
**Pull request by babakqci**
Added a tutorial for QBoost implementation of EQC models package.
## 🎥 Previews
- https://data-preview-83--qci-preview.netlify.app/learn/tutorials-and-use-cases/qboost-eqc-models
- https://data-preview-83--qci-preview.netlify.app/.github/workflows/deploy
- https://data-preview-83--qci-preview.netlify.app/learn/tutorials-and-use-cases/qboost-with-eqc-models-for-dirac-3

### CODE REVIEW

**Review by RussellHuffman — CHANGES_REQUESTED** [review]
Some of the math is not rendering correctly. You can see the issues on the preview url here: https://data-preview-83--qci-preview.netlify.app/learn/tutorials-and-use-cases/qboost-eqc-models

Our website supports the following Latex syntax

Screenshot 2024-08-02 at 2 52 24 PM

**Review by thisisaus — DISMISSED** [review]
Tutorial looks good. I was able to run the notebook without issue.

**Review by RussellHuffman — CHANGES_REQUESTED** [review]
I found two minor spelling errors:

> The data is then **splitted** into training and testing sets.


should be “split”

> We can echo some **statitics** on the training and testing sets,


should be “statistics”

To be consistent with our naming convention, I think it should be named "QBoost with EQC Models for Dirac-3". But I'm happy to discuss this last point.

**Comment by babakqci** [comment]
I addressed the issues

**Review by RussellHuffman — APPROVED** [review]
The updates look good. thank you!

**Pull request merged**
