### PR TITLE
Text addition/edits for Dirac-1 tutorials

### PR DESCRIPTION
**Pull request by nchancellor-qci**
Text added to all Dirac-1 based tutorials. The text is adding introduction, importance, applications, and conclusions. Code or more technical content has not been modified. EmuCore tutorials have not been touched as this requires more background research and is more appropriate as a separate PR. A goal of the added content is to make connections between tutorials and to provide literature with applications and provide general context, as well as to standardise the structure.

### CODE REVIEW

**Comment by nchancellor-qci** [comment]
I looked it up and the .DS_store file causing the conflict is a hidden file that Mac OS makes that stores information like the positions of folders. It snuck in on the last commit because I did commit -a rather than adding files individually to ensure nothing was missed. The must already be a .DS_store on main from someone else (or maybe me in the last PR) doing something similar. I think the correct solution here is just to delete all of the .DS_store files from the repo.

**Comment by nchancellor-qci** [comment]
I also added some files to the data folder, it may be cleaner to remove these so the folder is empty as it was before

**Comment by nchancellor-qci** [comment]
U.npy is another such file which was added, to the main folder, we may want to remove it

**Review by RussellHuffman — DISMISSED** [review]
I copy reviewed all of the text changes - not the code. My edits should be in place. In which case, I think this is good to go!

**Comment by nchancellor-qci** [comment]
> I copy reviewed all of the text changes - not the code. My edits should be in place. In which case, I think this is good to go!

No changes to code in this PR so probably no need to check, I'll pull the branch and do a commit with a few changes, including removing the file which is causing the conflicts.

**Comment by nchancellor-qci** [comment]
@RussellHuffman Files have now been removed should be able to merge now, and good-to-go from my perspective, I also read through everything and made some minor typo fixes

**Comment by thisisaus** [comment]
The text edits look good.

**Comment by RussellHuffman** [comment]
@thisisaus great! Will you approve the PR and then we'll merge it.

**Review by thisisaus — DISMISSED** [review]
Changes look good

**Review by thisisaus — DISMISSED** [review]
Attempt to resolve conflict remotely failed, will use web editor

**Review by RussellHuffman — APPROVED** [review]
approving

**Pull request merged**
