### PR TITLE
Code fixes for new client

### PR DESCRIPTION
**Pull request by nchancellor-qci**
Code fixes have been made to get client to work on all Dirac-1 tutorials. 

There is a serious outstanding issue with the portfolio optimisation tutorial though, the code runs but the data fail an assertion (details in code comments). This is after  a fix of a time zone problem recommended by Mark Camponelli, all of the client connection parts of this code work. 

There is also a more minor issue with the QAP tutorial, I couldn't figure out how to get the data imported for the final plot, I have pasted back in what it should be, but I am unable to reproduce this plot.

As a minor bit of standardisation, changed all tutorials to use the client in the way that the token is explicitly added in the notebook. There may be a longer term discussion of whether this is the right way to do it.

Russell recommended assigning to Babak, which is good because hopefully he can help fix the portfolio code as well as do a general code quality check.

### CODE REVIEW

**Comment by nchancellor-qci** [comment]
@babakqci I forgot to mention, but I think I need your help with the portfolio tutorial, but if you are too busy to review the rest of this please feel free to assign to someone else.

**Comment by babakqci** [comment]
@nchancellor-qci Which version of qci-client did you use to test the tutorials? Are you using qci-client-3.2.1?

**Review by rafikalid — DISMISSED** [review]

**Comment by nchancellor-qci** [comment]
> @nchancellor-qci Which version of qci-client did you use to test the tutorials? Are you using qci-client-3.2.1?

I am using the client from this  MR `https://git.qci-dev.com/qci-dev/qci-client/-/merge_requests/83` Mark pointed out that I could install it with `pip install git+https://git.qci-dev.com/qci-dev/qci-client.git@QCIEN-2587_consistent_results`

**Review by RussellHuffman — APPROVED** [review]
Read over everything for spelling and grammar. I can't speak to the code updates as much. approving the copy.

**Review by babakqci — APPROVED** [review]

**Pull request merged**
